name: Build and Push Multi-Arch Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Optional: use a specific image that has docker-cli pre-installed
    container:
      image: catthehacker/ubuntu:act-latest
      privileged: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker-registry.dolphin-puffin.ts.net/bursar:latest
            docker-registry.dolphin-puffin.ts.net/bursar:v${{ gitea.run_number }}